@port = 5033
@route = kommentar



### GET ALLE

GET http://localhost:{{port}}/{{route}}



### GET UD FRA ID

GET http://localhost:{{port}}/{{route}}/5f6e1c174994a38e5078b805



### GET ALLE KOMMENTARER UD FRA ET PRODUKTS ID

GET http://localhost:{{port}}/{{route}}/produkt/5f670f0dd1be3e2fd0cb2637



### GET KOMMENTARER UD FRA EN BRUGERS ID

GET http://localhost:{{port}}/{{route}}/bruger/5f6dae4f89b7d73ad47cfbea



### POST

POST http://localhost:{{port}}/{{route}}/admin
content-type: application/json

{
     "titel" : "Jeg elsker brød",
     "kommentaren" : "Vil bare sige, at jeg elsker brød",
     "bruger": "5f65c808485b6f9980b576b7",
     "produkt": "5f671954d1be3e2fd0cb2647"
}



### PUT - der kan kun rettes i titel og kommentar (øvrige felter giver ikke mening)

PUT http://localhost:{{port}}/{{route}}/admin/5f7064588c7e987d6044d555
content-type: application/json

{
     "titel" : "Jeg elsker brødet",
     "kommentaren" : "Vil bare sige, at jeg elsker brød"
}



### DELETE UD FRA ID

DELETE http://localhost:{{port}}/{{route}}/admin/5f7639bdf96ec14010fcd1ae