@port = 5033
@route = login


### LOGIN

POST http://localhost:{{port}}/{{route}}/login
content-type: application/json

{
    "email": "sha@mail.dk",
    "password": "suppe123"
}

## Se i ReadMe.txt for yderligere brugeres email og password

### LOGUD

GET http://localhost:{{port}}/{{route}}/logout



### LOGGEDIN?

GET http://localhost:{{port}}/{{route}}/loggedin
